### PR TITLE
Fix for missing attribute 'inline_instances' for django >=1.4

### PR DESCRIPTION
**Pull request by pielgrzym**
Apparently in django 1.4 or newer the `get_inline_instances` method is not being called before `get_formsets` so I made a dirty little fix to check if proper attribute is set and set it manually if it's not. I did not test this on django <1.4.

### CODE REVIEW

**Comment by magopian** [comment]
Wow, I totally lagged behind on this one, sorry @ppo, and thanks a lot @pielgrzym!

**Comment by magopian** [comment]
don't forget to add yourself to the AUTHORS file @pielgrzym ;)

**Comment by pielgrzym** [comment]
No problem, thanks for cool app :) the pull request included accidentally a feature with a link to export included for each export in exports list in admin :)

**Comment by magopian** [comment]
yep saw that, i'm just thinking about making it i18n. I think i'll do that, and publish a new version on PyPI

**Comment by pielgrzym** [comment]
Good idea :) I'm working on filter mechanism - I need to have ability to define querysets for exports like: export items with `field1 >= N` or `date_field__gte=1999-01-01` etc.

**Comment by magopian** [comment]
uploaded a new version ;)

**Pull request merged**
